"""Interactive Telethon StringSession generator.

Run:
    python -m collector_events.events_extractors.telegram_session_auth

The script asks for the Telegram login details, receives the authorization
code, and writes an env-compatible file next to this module:

    telegram_session.env

That file contains TELEGRAM_SESSION=<StringSession>. Treat it like a password.
"""

from __future__ import annotations

import argparse
import asyncio
import getpass
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from telethon import TelegramClient
from telethon.errors import PhoneCodeExpiredError, PhoneCodeInvalidError, SessionPasswordNeededError
from telethon.sessions import StringSession


THIS_FILE = Path(__file__).resolve()
EXTRACTOR_DIR = THIS_FILE.parent
PACKAGE_ROOT = THIS_FILE.parents[1]
SERVICE_ROOT = THIS_FILE.parents[2]
DEFAULT_OUTPUT_FILE = EXTRACTOR_DIR / "telegram_session.env"


def _load_env_value(key: str) -> str:
    value = os.getenv(key, "").strip()
    if value:
        return value

    for env_file in (SERVICE_ROOT / ".env", PACKAGE_ROOT / ".env"):
        if not env_file.exists():
            continue
        try:
            for line in env_file.read_text(encoding="utf-8").splitlines():
                clean = line.strip()
                if not clean or clean.startswith("#") or "=" not in clean:
                    continue
                name, raw_value = clean.split("=", 1)
                if name.strip() == key:
                    return raw_value.strip().strip('"').strip("'")
        except OSError:
            continue
    return ""


def _mask(value: str, *, visible: int = 4) -> str:
    if not value:
        return ""
    if len(value) <= visible * 2:
        return "*" * len(value)
    return f"{value[:visible]}...{value[-visible:]}"


def _prompt_value(label: str, *, default: str = "", secret: bool = False) -> str:
    suffix = f" [{_mask(default)}]" if default else ""
    prompt = f"{label}{suffix}: "
    if secret:
        value = getpass.getpass(prompt).strip()
    else:
        value = input(prompt).strip()
    return value or default


def _prompt_api_id(default: str) -> int:
    while True:
        value = _prompt_value("TELEGRAM_API_ID", default=default)
        try:
            return int(value)
        except ValueError:
            print("TELEGRAM_API_ID precisa ser um número inteiro.")


def _write_session_file(path: Path, session: str, metadata: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by collector_events.events_extractors.telegram_session_auth",
        "# Sensitive credential. Do not commit or share this file.",
        f"# generated_at={datetime.now(timezone.utc).isoformat(timespec='seconds')}",
    ]
    for key, value in metadata.items():
        lines.append(f"# {key}={value}")
    lines.extend(
        [
            "",
            f"TELEGRAM_SESSION={session}",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


async def generate_session(args: argparse.Namespace) -> None:
    api_id = _prompt_api_id(args.api_id or _load_env_value("TELEGRAM_API_ID"))
    api_hash = _prompt_value(
        "TELEGRAM_API_HASH",
        default=args.api_hash or _load_env_value("TELEGRAM_API_HASH"),
        secret=not bool(args.api_hash or _load_env_value("TELEGRAM_API_HASH")),
    )
    if not api_hash:
        raise RuntimeError("TELEGRAM_API_HASH é obrigatório.")

    phone = _prompt_value("Telefone Telegram no formato internacional, exemplo +5511999999999")
    if not phone:
        raise RuntimeError("Telefone é obrigatório para criar a sessão.")

    output_file = Path(args.output_file).resolve()
    client = TelegramClient(StringSession(), api_id, api_hash, connection_retries=3)

    print("\nConectando ao Telegram...")
    await client.connect()
    try:
        if not await client.is_user_authorized():
            print("Enviando código de autorização. Confira Telegram app primeiro; SMS pode vir como fallback.")
            sent = await client.send_code_request(phone)

            while True:
                code = input("Código recebido: ").strip().replace(" ", "")
                try:
                    await client.sign_in(phone=phone, code=code, phone_code_hash=sent.phone_code_hash)
                    break
                except PhoneCodeInvalidError:
                    print("Código inválido. Tente novamente.")
                except PhoneCodeExpiredError as exc:
                    raise RuntimeError("Código expirou. Rode o script novamente para pedir outro código.") from exc
                except SessionPasswordNeededError:
                    password = getpass.getpass("Senha 2FA do Telegram: ")
                    await client.sign_in(password=password)
                    break

        me = await client.get_me()
        session = client.session.save()
        if not session:
            raise RuntimeError("Telethon não retornou uma StringSession.")

        _write_session_file(
            output_file,
            session,
            {
                "account_id": getattr(me, "id", ""),
                "username": getattr(me, "username", "") or "",
                "phone": phone,
            },
        )

        print("\nSessão criada com sucesso.")
        print(f"Arquivo: {output_file}")
        print("Use o valor TELEGRAM_SESSION desse arquivo no .env do collector_events, ou carregue-o antes do relay.")
        print("Importante: rode apenas um coletor por TELEGRAM_SESSION para evitar AUTH_KEY_DUPLICATED.")
    finally:
        await client.disconnect()


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a Telethon TELEGRAM_SESSION file.")
    parser.add_argument(
        "--output-file",
        default=str(DEFAULT_OUTPUT_FILE),
        help="Env-compatible file where TELEGRAM_SESSION will be written.",
    )
    parser.add_argument("--api-id", default="", help="Telegram API ID. Defaults to env/.env when present.")
    parser.add_argument("--api-hash", default="", help="Telegram API hash. Defaults to env/.env when present.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    try:
        asyncio.run(generate_session(args))
    except KeyboardInterrupt:
        print("\nCancelado pelo usuário.")
    except Exception as exc:
        print(f"\nFalha ao gerar sessão: {type(exc).__name__}: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc


if __name__ == "__main__":
    main()
